### ISSUE TITLE
WebAssembly support?

### ISSUE THREAD

**Issue by djahandarie** [aatxe/irc#165]
I'd love to have the `proto` half of this repo available in wasm contexts, but the `client` half gets very in the way of that.

Would you be opening to either splitting up the crate or doing something with a feature flag?

**Comment by retep998** [comment]
Splitting up the crate is on the radar: https://crates.io/crates/irc-proto

**Comment by djahandarie** [comment]
Awesome. I just did a hackjob of splitting it to get my development started, but what I did probably is not useful for the actual split.

Darius

**Comment by aatxe** [comment]
It's not just on the radar, but it's already been done on the [`0.14`](https://github.com/aatxe/irc/tree/0.14) branch. There was a desire to wait until I had worked out #32 on [`fewer-allocations`](https://github.com/aatxe/irc/tree/fewer-allocations) before publishing `0.14` since it would be another breaking change, but I've been busy at work and not making progress there. So, maybe it's about time to cut a `0.14` release with the split crates (this is not the first time wanting to use `proto` has come up, of course).
