### ISSUE TITLE
Please consider publishing the irc-proto crate

### ISSUE THREAD

**Issue by belak** [aatxe/irc#193]
I've been working on building an IRC bot and ended up implementing my own IRC library, since it looked like this had a bunch of dependencies. It looks like the irc-proto crate exists, but hasn't been published. Would you consider publishing a version so people can build off of it?

**Comment by aatxe** [comment]
The main blocking factor here has been #32 (and the outstanding #179 PR which has stalled because I've been too busy to help drive it forward). I think it might be reasonable to cut a release of it earlier though, even before the 0.14 release (since I don't think it's actually likely to change much besides reducing allocations, especially not relative to the rest of the library).

**Comment by johnmaguire** [comment]
I'd like to put in another vote for getting the async API published.
