### ISSUE TITLE
Are `joined_chans` and `config_chans` accidentally switched here in `ClientState::handle_message`?

### ISSUE THREAD

**Issue by 8573** [aatxe/irc#204]
https://github.com/aatxe/irc/blob/751c56e85bd43ac6cf8589a8707b6c9b2409f102/src/client/mod.rs#L586-L592

I well may be misunderstanding, but this looks to me like "If we've joined a channel `C` that we weren't supposed to join, then join `C` again". Is it intended to be "If we've _not_ joined a channel `C` that we _were_ supposed to join, then join `C`"?

**Comment by aatxe** [comment]
The code directly above the part quoted joins anything that is in config_chans (using any keys that are defined in the configuration where appropriate). This code then attempts to rejoin anything that the client had already joined but was not specified in the configuration. In other words, this is an attempt at gracefully restoring channel membership after a disconnection. It's only an attempt because it's possible that some of the channels required an invitation or password to join, and thus this will fail.
