### ISSUE TITLE
when running I get error

### ISSUE THREAD

**Issue by foxjazz** [aatxe/irc#221]
Running `target\debug\examples\convertconf.exe -i client_config.json -o client_config.toml`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 2, kind: NotFound, message: "The system cannot 
find the file specified." })', examples\convertconf.rs:15:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\convertconf.exe -i client_config.json -o client_config.toml` (exit code: 101)

**Comment by aatxe** [comment]
The error looks to me like what occurs if the input file (client_config.json) was not present. Did you have such a file? Or do you mean to suggest that the program should report errors in a human readable fashion (as opposed to unwrapping them and causing the panic)? If the latter, I'm inclined to agree, but since convertconf is essentially a developer migration aide (from the old config format to the new one), it's been a low priority.
