### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by kamarkiewicz** [aatxe/irc#30]
Hey! Can you tell me how to establish an IRC client connection through a proxy server?

**Comment by aatxe** [comment]
This depends on what sort of proxy you're wishing to connect to. I suppose the normal way to do this would be to set up the system itself with a VPN connection or a SOCKS proxy. Then, all of the system's traffic (IRC included) will go through that. Otherwise, I don't know of any IRC-specific proxy tools.

**Comment by kamarkiewicz** [comment]
I would like to use SOCKS implementation available on https://github.com/alexcrichton/socks5-rs/ Is there an easy way to use v5::connect(..) with IRC client?

**Comment by aatxe** [comment]
There isn't really an easy way, no. You could make changes to integrate support for SOCKS proxies, but it wouldn't necessarily be straightforward given the current design. Additionally, the library you linked requires the Rust nightlies, and this library currently builds on stable (and I'd prefer to keep it that way). So, I'd be averse to accepting a pull request that integrates this right now anyway.

**Comment by QazCetelic** [comment]
For anyone reading this in the future. There is a crate feature `proxy` which adds support for SOCKS5 proxies.
