### ISSUE TITLE
Typo in comment?

### ISSUE THREAD

**Issue by Borkason** [aatxe/irc#73]
Shouldn't this say the following?

> /// Handles CTCP requests if the CTCP feature is **disabled**.

https://github.com/aatxe/irc/blob/master/src/client/server/mod.rs#L489

**Comment by aatxe** [comment]
So, strictly speaking, all the doc comments are written in a manner such that a reader can identify what features are toggleable. So, this says "enabled" because if you were reading it in docs, you wouldn't know necessarily which flag the docs were generated with. That being said, since this is a private function, I don't think the comment actually appears anywhere in the documentation. So, I suppose it wouldn't matter much either way.
